import type { Metadata } from "next"
import { Montserrat } from "next/font/google"

import { ThemeProvider } from "@/components/provider/theme-provider"
import { Header } from "@/components/ui/header"
import { SmoothScroll, ScrollTop } from "@/components/widget/scroll"

import "./globals.css"

const font = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScroll>
            <Header />
            <main>
              {children}
              <ScrollTop />
            </main>
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  )
}
